<?php

$testimonials = array(array('quote' => 'Product was exactly as described and shipping was fast. Totally satisfied.',
						    'name'  => 'James'),
                      array('quote' => 'Great price, good packaging, and very fast shipping. Product arrived exactly as descriped. Thank you.',
					        'name'  => 'Daniel'),
                      array('quote' => 'Received quickly! Thanks',
						    'name'  => 'Rodney'),
                      array('quote' => 'Item worked perfect',
						    'name'  => 'Mike'),
                      array('quote' => 'Great quality and fit',
					     	'name'  => 'Jared'),
                      array('quote' => 'No hassel transaction. Got my belt when promised. My machine is up and running again',
						    'name'  => 'Marty'),
                      array('quote' => 'Thank you for an excelent product, and service',
						    'name'  => 'Marty'),
                      array('quote' => 'Smooth transaction and prompt shipping! Thanks',
					     	'name'  => 'Eric'),
                      array('quote' => 'Awesome very fast shipping will use every time',
					    	'name'  => 'eBay User'),
                      array('quote' => 'Everything I needed to get the job done. Fast shipping!',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Amazing Seller! Paid for product last night and it showed up today!',
					    	'name'  => 'eBay User'),
                      array('quote' => 'Vendor Worked very well with special shipping needs. Thanks a lot!!!',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Item was received as promised and in good condition, thank you!',
		     				'name'  => 'eBay User'),
                      array('quote' => 'Excellent Seller. More than satisfied. Will urge all my friends to use them also',
	    					'name'  => 'eBay User'),
                      array('quote' => 'Quick shipping of great product very appreciated! Thanks so much!',
				    		'name'  => 'eBay User'),
                      array('quote' => 'The fact that I will return to buy more from atvpartsconnection says it all.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Rocket fast shipping and an exceptional product, definitely would deal with again',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Great aftermarket replacement and price. Shipped quickly.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'The part arrived quickly, well packaged, and fit the ATV perfectly.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Awesome!!! Thanks for great product at a great price!!',
				    		'name'  => 'eBay User'),	
                      array('quote' => 'Great seller! Ordered wrong, returned and replaced. No hassle!!!!',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Fast Shipping. Good Packaging. Good Experience',
				    		'name'  => 'eBay User'),
                      array('quote' => 'This part is awesome. I will be buying another for the other side soon.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'An excellent vendor. This is my third item purchased from them.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Excellent ebay seller, fast shipping, low prices, I will continue to buy from them',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Fast shipping, Great communication, will buy from again! AWESOME SELLER',
				    		'name'  => 'eBay User'),
                      array('quote' => 'The best price. Quality goods.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Part arrived in good time and was as expected. Will buy from them again.',
				    		'name'  => 'eBay User'),		     
                      array('quote' => 'Easy transaction and a perfect replacement for a good price.',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Shipping was faster than expected and pleased with the product',
				    		'name'  => 'eBay User'),
                      array('quote' => 'Right on the money... will do business with them again...',
				    		'name'  => 'eBay User'),
                      array('quote' => 'I\'m very satisfyied with my purchase. Shipping was very prompt as well. Thanks',
				    		'name'  => 'eBay User')
					);
					
$key = array_rand($testimonials, 1);

echo '<div class="testimonial">&ldquo;' . $testimonials[$key]['quote'] . '&rdquo;</div>';
echo '<div class="author">&mdash; ' . $testimonials[$key]['name'] . '</div>';
?>
